#!/usr/bin/env python
"""
analysis_v10.py — Core Evidence Package + Research Inventory

Restructured around advisor feedback (2026-05-26):
  - Central story = leapfrogging toward higher-order transformation under
    institutional shocks. All other findings demoted to inventory.
  - Capability-before-mission (v9 Section C) moved out of core report into
    research inventory as candidate future paper.
  - Each core figure explicitly tagged ESSENTIAL vs SUPPORTING.
  - Strongest-vs-Suggestive assessment replaces v9 Section D.

Outputs:
  analysis_v10_core.html         — focused leapfrogging story (paper-ready)
  research_inventory.html        — preserved findings for future papers
  *.csv                          — same numeric outputs as v9 (reused via import)
  latex/figures/*.png            — research-grade figures for the LaTeX paper
                                   (generated by paper_figures.py)
"""

from pathlib import Path

import numpy as np
import pandas as pd

import analysis_v9 as v9
import paper_figures

ROOT = Path(__file__).resolve().parents[2]
OUT  = ROOT / "experiments/reports/analysis_v10"
OUT.mkdir(parents=True, exist_ok=True)

# Redirect v9's output writes into v10's directory so CSVs land in one place
v9.OUT = OUT

LEVEL_META = v9.LEVEL_META
LEVEL_COLS = v9.LEVEL_COLS
CUT1, CUT2 = v9.CUT1, v9.CUT2


# ---------------------------------------------------------------------------
# HTML utilities
# ---------------------------------------------------------------------------

def _img_tagged(b64, caption, tag):
    """Render figure with an ESSENTIAL or SUPPORTING badge."""
    if b64 is None:
        return '<p class="missing">Figure not available.</p>'
    badge_class = "badge-essential" if tag == "ESSENTIAL" else "badge-supporting"
    return (
        f'<figure class="fig-{tag.lower()}">'
        f'<div class="badge {badge_class}">{tag}</div>'
        f'<img src="data:image/png;base64,{b64}" style="max-width:100%">'
        f'<figcaption>{caption}</figcaption>'
        f'</figure>'
    )


def _df_to_html(df, title=""):
    return v9._df_to_html(df, title=title)


# ---------------------------------------------------------------------------
# Strongest-vs-Suggestive assessment
# ---------------------------------------------------------------------------

def _strength_table(b, e):
    eff_df = b.get("eff_df", pd.DataFrame())
    bkp_df = b.get("bkp_df", pd.DataFrame())
    sn_df  = e.get("sn_df",  pd.DataFrame())
    sharp_df = e.get("sharp_df", pd.DataFrame())

    if len(eff_df):
        eff_1877 = eff_df[eff_df["Reform"] == 1877].set_index("Code")["Norm. effect size"]
        L4_1877  = eff_1877.get("L4", float("nan"))
        L3_1877  = eff_1877.get("L3", float("nan"))
        L1_1877  = eff_1877.get("L1_inv", float("nan"))
        L2_1877  = eff_1877.get("L2", float("nan"))
    else:
        L4_1877 = L3_1877 = L1_1877 = L2_1877 = float("nan")

    bkp_map = bkp_df.set_index("Code")["Rel. magnitude"].to_dict() if len(bkp_df) else {}
    snr_map = sn_df.set_index("Code")["Signal-to-noise ratio"].to_dict() if len(sn_df) else {}

    rows = [
        {
            "Claim": "Reform Acts are sharp strategic discontinuities (not gradual drift)",
            "Strength": "STRONGEST",
            "Quantitative basis": (
                f"E1 signal-to-noise ≥ 1.5× for L1 and L3 at 1854; "
                f"E2 sharpness ~6–10× above linear-trend expectation for L1/L2/L3"
            ),
            "Key figures": "E1, E2",
            "Caveats": "L4's small absolute scale makes its raw SNR look low; relative break (B3) is the cleaner read for L4.",
        },
        {
            "Claim": "Higher-order dimensions (L3/L4) respond disproportionately to reform shocks",
            "Strength": "STRONGEST",
            "Quantitative basis": (
                f"L4 normalised 1877 effect = {L4_1877:.2f}× pre-reform mean vs "
                f"L1 = {L1_1877:.2f}×, L2 = {L2_1877:.2f}×. "
                f"L4 relative break = {bkp_map.get('L4', float('nan')):.2f}× vs "
                f"L2 = {bkp_map.get('L2', float('nan')):.2f}×."
            ),
            "Key figures": "B2, B3",
            "Caveats": "Different denominator scales for each level — read as relative magnitudes, not absolute shares.",
        },
        {
            "Claim": "Visual leapfrogging signature in normalised trajectories",
            "Strength": "STRONG",
            "Quantitative basis": (
                "L4 grows multiple-fold above 1820–1853 baseline post-reform; "
                "L1 and L2 stay near 1.0 throughout post-reform period."
            ),
            "Key figures": "B1",
            "Caveats": "Descriptive, not statistically tested as a single claim.",
        },
        {
            "Claim": "Differential timing of reform response across levels",
            "Strength": "STRONG",
            "Quantitative basis": (
                "Event-time plots show L3 kink at 1854, L4 break at 1877; "
                "L1/L2 show no visible kink at either reform."
            ),
            "Key figures": "B5",
            "Caveats": "Visual, no formal test of differential break dates.",
        },
        {
            "Claim": "Post-reform acceleration is concentrated in strategic dimensions",
            "Strength": "SUGGESTIVE",
            "Quantitative basis": (
                "1877–1900 % change in 10-yr rolling mean: "
                "L4 +266%, L3 +113%, L1 +8%, L2 +4%."
            ),
            "Key figures": "B4",
            "Caveats": "% changes off small bases for L4; sensitive to window choice.",
        },
        {
            "Claim": "Two distinct reform patterns: 1854 disruption, 1877 acceleration",
            "Strength": "SUGGESTIVE",
            "Quantitative basis": (
                "Signs of L3/L4 ITS coefficients flip between 1854 (negative) and 1877 (positive)."
            ),
            "Key figures": "B2, B5",
            "Caveats": "Two events is a small sample for a 'pattern'.",
        },
        {
            "Claim": "Capability (L3) precedes mission (L4) in the pre-industrial era",
            "Strength": "SUGGESTIVE",
            "Quantitative basis": (
                "Rolling 30-yr correlation: L3 leads L4 by 5yr advantage 0.5–0.7 in pre-1750 windows; "
                "after ~1750 movement is synchronous. "
                "First-difference cross-correlation peak NOT statistically significant."
            ),
            "Key figures": "(in inventory — not core report)",
            "Caveats": "Direction consistent but formal cross-lag tests on detrended series are null. Moved to inventory as candidate future paper.",
        },
    ]

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "strength_assessment.csv", index=False)
    return df


# ---------------------------------------------------------------------------
# Core report HTML
# ---------------------------------------------------------------------------

CORE_CSS = """
body{font-family:Arial,sans-serif;max-width:1200px;margin:40px auto;padding:0 20px;color:#222}
h1{font-size:1.6em;border-bottom:2px solid #2c3e50;padding-bottom:8px}
h2{font-size:1.3em;color:#2c3e50;margin-top:36px}
h3{font-size:1.08em;color:#34495e}
table{border-collapse:collapse;width:100%;margin:14px 0;font-size:0.88em}
th{background:#2c3e50;color:white;padding:7px 10px;text-align:left}
td{border:1px solid #ddd;padding:6px 10px;vertical-align:top}
tr:nth-child(even){background:#f9f9f9}
figure{margin:18px 0;position:relative}
figcaption{font-size:0.82em;color:#555;margin-top:4px}
figure img{border:1px solid #ddd;border-radius:4px;width:100%}
.badge{display:inline-block;font-size:0.7em;font-weight:bold;letter-spacing:0.05em;
       padding:3px 8px;border-radius:3px;margin-bottom:6px}
.badge-essential{background:#117a65;color:white}
.badge-supporting{background:#909497;color:white}
.fig-essential{border-left:4px solid #117a65;padding-left:12px}
.fig-supporting{border-left:4px solid #d5dbdb;padding-left:12px;opacity:0.92}
.callout{background:#eaf4fb;border-left:4px solid #2980b9;padding:12px 16px;margin:16px 0;border-radius:4px}
.warn{background:#fef9e7;border-left:4px solid #f39c12;padding:12px 16px;margin:16px 0;border-radius:4px}
.headline{background:#eafaf1;border-left:6px solid #117a65;padding:16px 20px;margin:20px 0;border-radius:4px}
.missing{color:#888;font-style:italic}
code{background:#f4f4f4;padding:2px 5px;border-radius:3px;font-size:0.9em}
.section{background:#fafafa;border:1px solid #e0e0e0;border-radius:6px;padding:16px 20px;margin:24px 0}
.strong-tag{display:inline-block;padding:2px 8px;border-radius:3px;font-size:0.78em;font-weight:bold;color:white}
.tag-strongest{background:#117a65}
.tag-strong{background:#1f618d}
.tag-suggestive{background:#b9770e}
@media print {
  body{max-width:none;margin:20px;padding:0}
  h2{page-break-before:always}
  h2:first-of-type{page-break-before:auto}
  h3{page-break-after:avoid}
  figure,table,.callout,.warn,.section,.headline{page-break-inside:avoid}
}
"""


def build_core_html(a, b, e, strength_df):
    eff_df = b.get("eff_df", pd.DataFrame())
    bkp_df = b.get("bkp_df", pd.DataFrame())

    if len(eff_df):
        eff_1877 = eff_df[eff_df["Reform"] == 1877].set_index("Code")["Norm. effect size"]
        L4_1877 = eff_1877.get("L4", float("nan"))
        L1_1877 = eff_1877.get("L1_inv", float("nan"))
        L2_1877 = eff_1877.get("L2", float("nan"))
    else:
        L4_1877 = L1_1877 = L2_1877 = float("nan")

    bkp_map = bkp_df.set_index("Code")["Rel. magnitude"].to_dict() if len(bkp_df) else {}

    # Strength table as HTML with coloured tags
    def _tag_html(s):
        cls = {"STRONGEST": "tag-strongest", "STRONG": "tag-strong", "SUGGESTIVE": "tag-suggestive"}.get(s, "tag-suggestive")
        return f'<span class="strong-tag {cls}">{s}</span>'

    strength_rows_html = "".join(
        f"<tr><td>{r['Claim']}</td><td>{_tag_html(r['Strength'])}</td>"
        f"<td>{r['Quantitative basis']}</td><td>{r['Key figures']}</td>"
        f"<td>{r['Caveats']}</td></tr>"
        for _, r in strength_df.iterrows()
    )
    strength_table_html = (
        '<table><thead><tr><th>Claim</th><th>Strength</th>'
        '<th>Quantitative basis</th><th>Key figures</th><th>Caveats</th></tr></thead>'
        f'<tbody>{strength_rows_html}</tbody></table>'
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">
<title>Analysis v10 — Core Evidence: Leapfrogging</title>
<style>{CORE_CSS}</style>
</head>
<body>

<h1>Analysis v10: Core Evidence Package — Leapfrogging</h1>
<p><em>Oxford University Ledgers, 1700–1900. Restructured around advisor feedback (2026-05-26): focused core evidence for leapfrogging story; secondary findings preserved in companion <a href="research_inventory.html">research inventory</a>.</em></p>

<div class="headline">
<strong>Central claim:</strong> Institutional shocks (1854 &amp; 1877 Reform Acts) triggered
<em>leapfrogging</em> toward higher-order transformation — capability expansion (L3) and
mission redefinition (L4) — before lower-order operational optimisation (efficiency L1,
process L2) was completed. The Reform Acts function as <em>strategic discontinuities</em>
rather than gradual modernisation triggers.
</div>

<div class="callout">
<strong>What's essential vs supporting:</strong> Figures marked
<span class="badge badge-essential">ESSENTIAL</span> carry the leapfrogging argument and
belong in the manuscript. Figures marked
<span class="badge badge-supporting">SUPPORTING</span> add texture but can be moved to
appendix or dropped without weakening the core claim. The
<a href="#strength">Strength assessment</a> at the bottom maps each sub-claim to its
quantitative basis.
</div>

<!-- ========================================================= SEC 1 -->
<h2>1. Framework: Four Dimensions of Transformation</h2>
<div class="section">
<p>The four-level framework is treated as <em>dimensions</em> of transformation, not
deterministic stages. The empirical question is which dimensions activate first, and
under what institutional conditions.</p>
{a["dim_table"]}
{_img_tagged(a["b64_trends"],
             "Figure 1. Four transformation dimensions (1700–1900). Red dashed lines = 1854 &amp; 1877 Reform Acts.",
             "ESSENTIAL")}
</div>

<!-- ========================================================= SEC 2 -->
<h2>2. The Leapfrogging Mechanism (Core Evidence)</h2>

<div class="callout">
<strong>Mechanism in one sentence:</strong> Higher-order dimensions (L3 capability, L4 mission)
exhibit disproportionately larger responses to institutional shocks than lower-order
dimensions (L1 efficiency, L2 process). Three quantitative angles below — normalised
trajectories, normalised ITS effects, and break magnitudes.
</div>

<div class="section">
<h3>2.1 Normalised Growth Trajectories</h3>
<p>Each level rescaled to its 1820–1853 pre-reform mean (= 1). If transformation were
uniform across dimensions, all four trajectories would diverge similarly. The visible
divergence — L4 rising multiple-fold while L1/L2 stay near baseline — is the leapfrogging
signature.</p>
{_img_tagged(b.get("b64_norm"),
             "Figure 2 (B1). Normalised growth trajectories, 1820–1900. All levels scaled to pre-reform baseline = 1.",
             "ESSENTIAL")}
</div>

<div class="section">
<h3>2.2 Normalised ITS Effect Sizes</h3>
<p>Interrupted time-series level-shift coefficients at each Reform Act, divided by each
level's own pre-reform mean. Removes scale differences so levels can be compared directly.</p>
{_img_tagged(b.get("b64_effects"),
             "Figure 3 (B2). Normalised ITS effect sizes (level shift / pre-reform mean) at each Reform Act.",
             "ESSENTIAL")}
{_df_to_html(eff_df, title="ITS Effect Sizes")}
<p><strong>Headline:</strong> At 1877, L4 effect = <strong>{L4_1877:.2f}×</strong>
its pre-reform mean — roughly <strong>{L4_1877/L1_1877:.0f}× larger than L1</strong>
({L1_1877:.2f}×) and <strong>{L4_1877/L2_1877:.0f}× larger than L2</strong>
({L2_1877:.2f}×). At 1854, both L3 and L4 show large negative shifts (disruption pattern)
while L1/L2 barely move.</p>
</div>

<div class="section">
<h3>2.3 Break Magnitude Comparison</h3>
<p>Structural break magnitudes (binary segmentation) relative to each level's
pre-break mean. The single largest piece of leapfrogging evidence in the dataset.</p>
{_img_tagged(b.get("b64_bkp_mag"),
             "Figure 4 (B3). Relative break magnitude by level.",
             "ESSENTIAL")}
{_df_to_html(bkp_df, title="Break Magnitudes")}
<p><strong>Headline:</strong> L4 relative break magnitude = <strong>{bkp_map.get('L4', float('nan')):.2f}×</strong> —
roughly an order of magnitude larger than the operational dimensions. The mission dimension's
structural shift dwarfs everything in the operational axis.</p>
</div>

<!-- ========================================================= SEC 3 -->
<h2>3. Reform Acts as Strategic Discontinuities</h2>
<div class="callout">
Two complementary tests of whether the 1854 reform was a discontinuous jump or just a
phase of fast linear change. Both reject the gradual-drift interpretation.
</div>

<div class="section">
<h3>3.1 Signal-to-Noise of Breaks</h3>
<p>Break magnitude at 1854 divided by the pre-reform rolling standard deviation
(10-year window average). High ratio = sharp shift relative to typical year-to-year noise.</p>
{_img_tagged(e.get("b64_snr"),
             "Figure 5 (E1). Signal-to-noise ratio of 1854 break by level.",
             "ESSENTIAL")}
{_df_to_html(e.get("sn_df", pd.DataFrame()), title="Signal-to-Noise by Level")}
</div>

<div class="section">
<h3>3.2 Sharpness Index</h3>
<p>Fraction of total post-1854 level gain that occurs within the first 5 years.
Under a linear trend, this fraction should equal 5/n_post_years (~0.135).
Observed values 6–10× larger ⇒ change concentrated immediately post-reform, not spread evenly.</p>
{_img_tagged(e.get("b64_sharp"),
             "Figure 6 (E2). Sharpness of reform response. Blue = observed; grey = linear-trend expectation.",
             "ESSENTIAL")}
{_df_to_html(e.get("sharp_df", pd.DataFrame()), title="Sharpness Index by Level")}
</div>

<!-- ========================================================= SEC 4 -->
<h2>4. Supporting Evidence</h2>
<div class="callout">
The figures below add texture to the leapfrogging story but are not load-bearing.
They would belong in the appendix, not the main figures of a manuscript.
</div>

<div class="section">
<h3>4.1 Post-Reform Acceleration</h3>
{_img_tagged(b.get("b64_accel"),
             "Figure 7 (B4). Post-reform acceleration by level and window.",
             "SUPPORTING")}
{_df_to_html(b.get("accel_df", pd.DataFrame()), title="Post-Reform Acceleration")}
</div>

<div class="section">
<h3>4.2 Event-Time Plots Around Each Reform Act (All Four Levels)</h3>
{_img_tagged(b.get("b64_event"),
             "Figure 8 (B5). Event-time plots around each Reform Act for all four levels.",
             "SUPPORTING")}
</div>

<div class="section">
<h3>4.3 Era-Level Descriptives</h3>
{a["era_table"]}
</div>

<!-- ========================================================= SEC 5 -->
<h2 id="strength">5. Strongest vs Suggestive — Claim-by-Claim</h2>
<div class="callout">
Per advisor request: explicit assessment of which sub-claims are strongest vs only
suggestive. Two top-line claims (sharp discontinuity, disproportionate higher-order response)
are STRONGEST. Capability-before-mission has been moved to the
<a href="research_inventory.html">research inventory</a> as a candidate future paper —
direction is consistent but rigorous tests on detrended series are null.
</div>
<div class="section">
{strength_table_html}
</div>

<!-- ========================================================= SEC 6 -->
<h2>6. Paper Skeleton (Leapfrogging-Centred)</h2>
<div class="section">

<h3>6.1 Research question</h3>
<p>Do organisations facing major institutional shocks transform through a predictable
operational-first sequence, or do they leapfrog directly into higher-order capability
and mission transformation? Using 200 years of Oxford University accounting ledgers
(1700–1900), we ask whether external reforms can short-circuit the
efficiency-then-redesign sequence assumed in many technology-adoption models.</p>

<h3>6.2 Theoretical motivation</h3>
<ul>
<li><strong>Punctuated equilibrium:</strong> institutional shocks may trigger simultaneous
multi-dimensional reorganisation, bypassing lower-order stages.</li>
<li><strong>Resource-based view + slack:</strong> endowment-funded organisations may have
the financial capacity to leapfrog; fiscally-constrained organisations may not.</li>
<li><strong>AI analogy:</strong> contemporary firms investing in AI talent and org redesign
before optimising operations may be rationally responding to external pressure rather
than aberrantly skipping stages.</li>
</ul>

<h3>6.3 Data &amp; identification</h3>
<ul>
<li>1,581 scanned ledger pages, annual panel of real-£ expenditure shares by category.</li>
<li>Treatment: 1854 University Reform Act and 1877 University of Oxford Act (exogenous
parliamentary timing).</li>
<li>Identification: interrupted time series (ITS) with HAC standard errors;
structural-break detection (binseg); signal-to-noise and sharpness tests for the
discontinuous-vs-gradual distinction.</li>
</ul>

<h3>6.4 Main finding</h3>
<p>Reform Acts function as <strong>strategic discontinuities</strong> that produce
disproportionately large responses in higher-order dimensions (L3 capability, L4 mission)
relative to lower-order dimensions (L1 efficiency, L2 process). At the 1877 reform,
L4's normalised effect is <strong>{L4_1877:.2f}× pre-reform mean</strong> — roughly
{L4_1877/L1_1877:.0f}× larger than L1. L4's relative break magnitude
({bkp_map.get('L4', float('nan')):.2f}×) is an order of magnitude larger than L2
({bkp_map.get('L2', float('nan')):.2f}×). The 1854 reform shows the same asymmetry
in disruption: L3/L4 hit hardest in absolute terms, L1/L2 barely move.</p>

<h3>6.5 Mechanism</h3>
<p>External institutional pressure forces rapid capability investment (salary growth,
new appointments) and mission redefinition (educational expansion) before the
organisation can fully articulate a new strategic plan. Endowment-funded resource slack
(from rising land rents) provides the financial capacity to leapfrog; organisations
under fiscal constraint cannot. The leapfrogging of L1/L2 suggests external shocks can
short-circuit the efficiency-then-redesign sequence typically assumed in technology
adoption models.</p>

<h3>6.6 Contemporary AI parallel</h3>
<p>Firms investing in AI capability and org redesign ahead of operational optimisation
may be following the same shock-driven leapfrogging pattern Oxford exhibited under the
Reform Acts. Regulatory mandates around AI may function analogously to the 19th-century
Reform Acts — forcing higher-order transformation first.</p>

<h3>6.7 Boundary conditions</h3>
<ul>
<li>Transformation pace (200 years) is pre-industrial — not generalisable to AI tempo.</li>
<li>Oxford's no-competition / endowment-funded structure is unusual; analogy is to
well-capitalised firms with retained earnings, not to all firms.</li>
<li>Mechanism (shock-driven leapfrogging) is the generalisable contribution, not the pace.</li>
</ul>

</div>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Research inventory — separate HTML file
# ---------------------------------------------------------------------------

INVENTORY_CSS = """
body{font-family:Arial,sans-serif;max-width:1300px;margin:40px auto;padding:0 20px;color:#222}
h1{font-size:1.6em;border-bottom:2px solid #2c3e50;padding-bottom:8px}
h2{font-size:1.2em;color:#2c3e50;margin-top:32px}
table{border-collapse:collapse;width:100%;margin:14px 0;font-size:0.84em}
th{background:#2c3e50;color:white;padding:7px 10px;text-align:left;vertical-align:top}
td{border:1px solid #ddd;padding:7px 10px;vertical-align:top}
tr:nth-child(even){background:#f9f9f9}
.callout{background:#eaf4fb;border-left:4px solid #2980b9;padding:12px 16px;margin:16px 0;border-radius:4px}
.todo{color:#b9770e;font-weight:bold;font-style:italic}
.high{color:#117a65;font-weight:bold}
.medium{color:#1f618d}
.low{color:#909497}
.unrated{color:#b9770e;font-style:italic}
code{background:#f4f4f4;padding:2px 5px;border-radius:3px;font-size:0.9em}
"""

# Each row: (finding, empirical_support, method, source_artifact, theme_area)
INVENTORY_ROWS = [
    {
        "Finding": "Capability expansion precedes mission transformation (L3 → L4)",
        "Empirical support": (
            "Rolling 30-yr correlation shows L3 leading L4 by 5 yr in pre-1750 windows "
            "(advantage 0.5–0.7). First-difference cross-correlation peak directionally "
            "consistent but NOT statistically significant. First-entry timing threshold-sensitive."
        ),
        "Method": "Cross-lag with bootstrap CI; distributed lag (levels &amp; first-differences); rolling correlation; state-transition entry timing",
        "Source artifact": (
            'v9 Section C; '
            '<code>analysis_v9/bootstrap_crosscorr_L3_L4.csv</code>, '
            '<code>distributed_lag.csv</code>, '
            '<code>rolling_correlation.csv</code>, '
            '<code>state_transitions.csv</code>'
        ),
        "Theme": "Sequencing within strategic axis",
    },
    {
        "Finding": "Strict L1 → L2 → L3 → L4 ordering across transformation dimensions",
        "Empirical support": (
            "Change-point ordering partial (B3 confirms L4 has largest break, but break "
            "<em>year</em> ordering is mixed). Transition-date crossings sensitive to "
            "threshold choice; no robust strict ordering."
        ),
        "Method": "Binary segmentation change-point detection; transition-date crossings at quantile thresholds",
        "Source artifact": (
            '<code>analysis_v6/level_sequencing.csv</code>, '
            '<code>analysis_v6/structural_breaks.csv</code>, '
            '<code>analysis_v8/break_ordering.csv</code>, '
            '<code>analysis_v8/transition_dates.csv</code>'
        ),
        "Theme": "Sequencing across all four dimensions",
    },
    {
        "Finding": "Granger-causal chaining across levels (L_k predicts L_{k+1})",
        "Empirical support": (
            "Mostly insignificant across lag specifications and pairwise tests. "
            "No evidence of predictive chaining."
        ),
        "Method": "Sequential Granger causality (HAC-robust); local projections",
        "Source artifact": (
            '<code>analysis_v7/granger_results.csv</code>, '
            '<code>analysis_v7/local_projections_results.csv</code>, '
            '<code>analysis_v8/sequential_granger.csv</code>'
        ),
        "Theme": "Sequencing — predictive structure",
    },
    {
        "Finding": "Semantic / language modernisation (Latin → English shift, vocabulary evolution)",
        "Empirical support": (
            "English-share rises from low base across 18th century. "
            "Vocabulary diversification trends documented in standalone analyses."
        ),
        "Method": "Per-row language classification; vocabulary type-token ratios; text-trend analysis over enriched corpus",
        "Source artifact": (
            '<code>analysis/analysis_text_trends.py</code>, '
            '<code>analysis/analysis_vocabulary.py</code>, '
            'language fields in <code>experiments/results/enriched/</code>'
        ),
        "Theme": "Linguistic/cultural modernisation",
    },
    {
        "Finding": "Income diversification dynamics (concentration → diversification over time)",
        "Empirical support": (
            "Income-source concentration (HHI) declines across the 19th century as new "
            "categories enter; documented in v6."
        ),
        "Method": "Annual HHI of income categories; entry/exit accounting of revenue streams",
        "Source artifact": '<code>analysis_v6/income_diversification.csv</code>',
        "Theme": "Revenue / portfolio diversification",
    },
    {
        "Finding": "Charity institutionalisation (informal alms → formal endowment)",
        "Empirical support": (
            "Charity-related categories shift from ad-hoc disbursements to recurring/formalised "
            "payments over the 18th–19th centuries."
        ),
        "Method": "Category share decomposition; hypothesis-driven longitudinal analysis",
        "Source artifact": '<code>analysis/analysis_hypotheses.py</code>; enriched <code>category</code> field',
        "Theme": "Institutional formalisation",
    },
    {
        "Finding": "Corporate / market transition (in-kind &amp; ad-hoc → cash &amp; market-mediated)",
        "Empirical support": (
            "Direction of payment composition shifts toward salaried/regular money flows; "
            "decline of in-kind and one-off disbursements."
        ),
        "Method": "Payment-type composition over time; supplier-network structure",
        "Source artifact": (
            '<code>analysis/analysis_supplier_networks.py</code>; '
            'enriched <code>category</code>/<code>direction</code>/<code>payment_period</code> fields'
        ),
        "Theme": "Market formation",
    },
    {
        "Finding": "Payment modernisation (irregular → periodic, salary-based)",
        "Empirical support": (
            "L2 (payment-modernity index) rises smoothly across 1700–1900. "
            "Used as a transformation proxy throughout v9."
        ),
        "Method": "Payment-period regularity index aggregated per year; rolling 10-yr smoothing",
        "Source artifact": (
            '<code>analysis_v6/four_level_proxies.csv</code> (L2 column); '
            'payment_period field in enriched data'
        ),
        "Theme": "Process modernisation",
    },
    {
        "Finding": "Resource slack enables leapfrogging (endowment / land-rent income)",
        "Empirical support": (
            "Rising land-rent income provides financial capacity for capability investment "
            "during reform shock periods. Documented as a mechanism in v7."
        ),
        "Method": "Income composition decomposition; ITS on land-rent income alongside expenditure dimensions",
        "Source artifact": (
            '<code>analysis_v7/its_results.csv</code>, '
            '<code>analysis_v7/event_study_results.csv</code>'
        ),
        "Theme": "Enabling mechanism for leapfrogging (links back to main paper)",
    },
]


def build_inventory_html():
    rows_html = "".join(
        f"<tr>"
        f"<td><strong>{r['Finding']}</strong></td>"
        f"<td>{r['Empirical support']}</td>"
        f"<td>{r['Method']}</td>"
        f"<td>{r['Source artifact']}</td>"
        f"<td>{r['Theme']}</td>"
        f"<td class='todo'>TODO</td>"
        f"<td class='todo'>TODO</td>"
        f"<td class='todo'>TODO</td>"
        f"</tr>"
        for r in INVENTORY_ROWS
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8">
<title>Research Inventory — Historical Ledger Project</title>
<style>{INVENTORY_CSS}</style>
</head>
<body>

<h1>Research Inventory: Preserved Findings for Future Papers</h1>
<p><em>Companion to <a href="analysis_v10_core.html">analysis_v10_core.html</a> (the leapfrogging core
evidence package). Generated 2026-05-26 in response to advisor feedback.</em></p>

<div class="callout">
<strong>Purpose:</strong> The Oxford ledger corpus is unusually rich and supports several
distinct research questions beyond the leapfrogging core story. This inventory catalogues
each preserved finding with its empirical support, methodological approach, and source
artifact, so the archive can serve as a long-term research platform rather than a
single-paper project.
<br><br>
<strong>How to fill in:</strong> The last three columns (Confidence, Theory angle, Future-paper direction)
are deliberately left as <span class="todo">TODO</span> — they require theoretical judgment
that belongs with the authors, not auto-extraction.
Suggested ratings for Confidence: <span class="high">HIGH</span> /
<span class="medium">MEDIUM</span> / <span class="low">LOW</span>.
</div>

<h2>Preserved Findings</h2>

<table>
<thead><tr>
<th style="width:13%">Finding</th>
<th style="width:22%">Empirical support</th>
<th style="width:14%">Method</th>
<th style="width:14%">Source artifact</th>
<th style="width:10%">Theme</th>
<th style="width:7%">Confidence</th>
<th style="width:10%">Theory angle</th>
<th style="width:10%">Future-paper direction</th>
</tr></thead>
<tbody>
{rows_html}
</tbody>
</table>

<h2>How to use this inventory</h2>
<ul>
<li><strong>Each row = one candidate paper or supplementary contribution.</strong>
Group rows by Theme when scoping new papers.</li>
<li><strong>"Source artifact" columns are reproducible:</strong> the CSVs and scripts
listed exist in <code>experiments/reports/</code> and <code>experiments/analysis/</code>.</li>
<li><strong>Treat the three TODO columns as a working document.</strong> Update Confidence
when new evidence comes in; refine Theory angle and Future-paper direction as the
research programme matures.</li>
<li><strong>Capability-before-mission (row 1)</strong> is the most paper-ready candidate
beyond the core leapfrogging story — the rolling-correlation finding of pre-1750 lead-lag
shifting to post-1750 synchronicity is a distinctive empirical contribution in its own right.</li>
</ul>

</body>
</html>"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Loading main panel (via v9)...")
    panel_df = v9.load_main_panel()

    print("Section A: framework reframe...")
    a = v9.section_a(panel_df)

    print("Section B: leapfrogging analysis...")
    b = v9.section_b(panel_df)

    print("Section E: reform discontinuities...")
    e = v9.section_e(panel_df)

    print("Building strength assessment...")
    strength_df = _strength_table(b, e)

    print("Building core HTML report...")
    core_html = build_core_html(a, b, e, strength_df)
    core_path = OUT / "analysis_v10_core.html"
    core_path.write_text(core_html, encoding="utf-8")

    print("Building research inventory HTML...")
    inv_html = build_inventory_html()
    inv_path = OUT / "research_inventory.html"
    inv_path.write_text(inv_html, encoding="utf-8")

    print("Generating research-grade LaTeX figures (paper_figures.py)...")
    latex_fig_dir = OUT / "latex" / "figures"
    fig_paths = paper_figures.generate_all(latex_fig_dir)

    print(f"\nCore report:      {core_path}")
    print(f"Inventory:        {inv_path}")
    print(f"LaTeX figures:    {latex_fig_dir}")
    for p in fig_paths:
        print(f"  {p.name}")
    print("CSVs written to:", OUT)
    for f in sorted(OUT.glob("*.csv")):
        print(f"  {f.name}")


if __name__ == "__main__":
    main()
